### ISSUE TITLE
Front camera keeps rotating upside down

### ISSUE THREAD

**Issue by tobilvr** [nekocode/CameraFilter#13]
Hello nekocode. Am trying to use the front camera, but the view is rotated upside down. I tried camera.setDisplayOrientation(90); but didnt work as well as parameter.setRotation(90) . 

Please how can i go about this.  Thank you for the time invested in this library.

**Comment by nekocode** [comment]
@tobilvr  You can rotate the **[texture coord](https://github.com/nekocode/CameraFilter/blob/master/app/src/main/java/cn/nekocode/camerafilter/filter/CameraFilter.java#L53-L58)**.

```java
private static final float ROATED_TEXTURE_COORDS[] = {
        0.0f, 0.0f,
        0.0f, 1.0f,
        1.0f, 0.0f,
        1.0f, 1.0f,
};
```

**Comment by tobilvr** [comment]
It works ..I cannot thank you enough, I personally, am grateful for your work here. I still have another question tho., one in this issue and the other on a new issue.. :) 👍 

Is it safe, if i want to switch camera, and i destroy the backCamera renderer, and then instatiate a new FrontCameraRenderer which is then set to the same texture view

**Comment by tobilvr** [comment]
All working and done. Thanks

**Comment by Traz9g** [comment]
What i have to put in that massive to make landscape mode?

**Comment by shivam21** [comment]
@tobilvr can you please provide code on how to switch the camera.
