### ISSUE TITLE
How to make more custom filters from the Default filters

### ISSUE THREAD

**Issue by tobilvr** [nekocode/CameraFilter#14]
I rilly like the EmInterference, and would like to create another type of this which instead of green tone, will be yellow or red tones e.t.c as well as the "Contrast Filter", how can i go about this please. Thanks for the anticipated support :)

**Comment by nekocode** [comment]
Wow, it is another more complex topic. Maybe you should know more about the knowledges of OpenGL and shader.

**Comment by tobilvr** [comment]
Hello nekocode. Thanks for your directions. I have found a way to go about adding new filters. You are such a genius

**Comment by SohailYaseen** [comment]
can you share the way please! tobilvr
