### ISSUE TITLE
How to switch camera to front.

### ISSUE THREAD

**Issue by shivam21** [nekocode/CameraFilter#22]
Thanks for this awesome library,can you please help me to switch camera from back to front.

**Comment by savasadar** [comment]
same problem.

**Comment by onyx-wang** [comment]
`    private Pair<Camera.CameraInfo, Integer> getBackCamera() {
        Camera.CameraInfo cameraInfo = new Camera.CameraInfo();
        final int numberOfCameras = Camera.getNumberOfCameras();

        for (int i = 0; i < numberOfCameras; ++i) {
            Camera.getCameraInfo(i, cameraInfo);
            if (cameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_BACK) {
                return new Pair<>(cameraInfo, i);
            }
        }
        return null;
    }`
I think you can try CAMERA_FACING_FRONT !

**Comment by shivam21** [comment]
but i want to switch it in same fragment

**Comment by savasadar** [comment]
I fixed this issue. You should create TextureView from codebehind and remove and add view to your main layout every camera switched.

**Comment by shivam21** [comment]
can you please provide the code..actually i am trying this from an month
but unable to do so.

**Comment by savasadar** [comment]
@shivam21 of course

You should change setup method like this:

`void setupCameraPreviewView(boolean isFrontCamera) {
        parentLayout.removeView(textureView);

        textureView = new TextureView(this);
        textureView.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, Gravity.CENTER));

        parentLayout.addView(textureView);

        final CameraRenderer renderer = new CameraRenderer(this, isFrontCamera);
        assert textureView != null;
        textureView.setSurfaceTextureListener(renderer);
        textureView.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom) {
                if(renderer != null)
                    renderer.onSurfaceTextureSizeChanged(null, v.getWidth(), v.getHeight());
            }
        });`

and 
`public CameraRenderer(Activity context, boolean isFrontCamera) {
        this.context = context;
        this.isFrontCamera = isFrontCamera;
    }
`
and in CameraRenderer:

`// Open camera
        int cameraId;
        if(isFrontCamera)
            cameraId = getFrontCamera();
        else
            cameraId = getBackCamera();

        camera = Camera.open(cameraId);`

I hope this help you.

**Comment by shivam21** [comment]
@savasadar thanks a lot.
