### ISSUE TITLE
Camera access is required

### ISSUE THREAD

**Issue by zhangkom** [nekocode/CameraFilter#40]
I just run on android studio3.1.2, but when app run, show this error:"Camera access is required". And I look at the source .code, it is here, how can I resolve this bug?
   
     if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.CAMERA)
                != PackageManager.PERMISSION_GRANTED && permit) {

            // Should we show an explanation?
            if (ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.CAMERA)) {
                Toast.makeText(this, "Camera access is required.", Toast.LENGTH_SHORT).show();

            } else {
                ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.CAMERA},
                        REQUEST_CAMERA_PERMISSION);
            }

        } else {
            setupCameraPreviewView();
        }

**Comment by nekocode** [comment]
Manully grant camera access permission to this app.

**Comment by zhangkom** [comment]
when I open app, no a dialogue or other method to pop, just  a message "Camera access is required", how can I manully give access of camera?

**Comment by nekocode** [comment]
In system setting.
