### ISSUE TITLE
 在显示自定义照相界面调用照相机api回调result_code=0 In the display of the custom camera interface to call the camera API callback result_code=0

### ISSUE THREAD

**Issue by qssq** [nekocode/CameraFilter#9]
I have a Project dialog box pop-up options are to achieve the switch call comes with the camera's current interface display video camera, that is, the use of your framework, as well as the call to select the local album API
I called the interface initialization after the start of the preview, and then call the system comes with a camera callback is always 0 activity.RESULT_CODE=CANNEL, which is how it happened? As well as the choice of album came back and then click to take pictures
Thread already started va.lang.IllegalThreadStateException:
Java.lang.Thread.checkNotStarted at (Thread.java:849)
Java.lang.Thread.start at (Thread.java:1059)
Cn.nekocode.camerafilter.CameraRenderer.onSurfaceTextureAvailable at (CameraRenderer.java:121)

**Comment by nekocode** [comment]
@qssq 你用中文描述吧，这机翻的英文我表示看不懂啊。

**Comment by qssq** [comment]
是这样的 有一个界面 加载后我就调用你这个项目的api进行预览了，但是这个预览界面上面还有一层显示界面 然后呢还有一个对话框  就是有几个行为 ，当前界面预览拍照，以及选择相册 选择自带相机拍照，我使用了当前预览界面拍照后 然后选择 相册后返回 崩溃了 ，就是之前反馈的线程问题， 然后还导致了自带相机返回值 一直为0 RESULT_CODE =0 很纳闷啊。

**Comment by nekocode** [comment]
能分享你目前的代码给我么？我帮检查下具体是什么问题。

**Comment by qssq** [comment]
谢谢，是真实项目 太乱 又太啰嗦。 估计只能分享一个j横截面了。。 其实我上面描述的应该很清楚呀。同一个界面实现拍照 以及 拍照后的 图片ps也就是 合成 头发虚拟发型 同一个界面进行操作，所以在textstrue上面有一个图层  没有选择对话框的拍照选项时照相机是被隐藏的，显示后就调用了拍照方法 完全复制您上面demo里面的代码 直接拍照没问题就是选择一个本地相册api然后再重新选择照相就崩溃了线程错误 ，然后就是  自带相机回调失败，我也搞不懂。

**Comment by nekocode** [comment]
你可以尝试在 [这一行](https://github.com/nekocode/CameraFilter/blob/master/app/src/main/java/cn/nekocode/camerafilter/CameraRenderer.java#L102) 和 [这一行](https://github.com/nekocode/CameraFilter/blob/master/app/src/main/java/cn/nekocode/camerafilter/CameraRenderer.java#L110) 分别设置断点。检查跳转到相册选择界面时是否调用了渲染线程的 `interrupt()` 方法，以及返回到渲染界面时 `isAlive()` 是否返回 `false`（简而言之就是判断线程的状态）。
